#pragma once

enum class ItemId {
	NONE = -1,
	DIRT_BLOCK_ITEM = 0,
	GRASS_BLOCK_ITEM,
	STONE_BLOCK_ITEM,
	SAND_BLOCK_ITEM,
	SNOWY_GRASS_BLOCK_ITEM,
	OAK_LOG_BLOCK_ITEM,
	LEAVES_BLOCK_ITEM,
	PLANK_BLOCK_ITEM,
	STICK_ITEM,
	LAST_ITEM
};